chore: draft an install script for easy installation

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,12 +1,12 @@
 #!/bin/bash
 
-################################################################################
-# NOT WELL TESTED, USE IT OWN YOUR OWN RISK
-################################################################################
+# some parts are taken from:
+# https://get.sdkman.io
+# https://raw.githubusercontent.com/goreleaser/get/master/get
 
-# some parts are taken from: https://get.sdkman.io
-
-todarch_bash_profile="${HOME}/.bash_profile"
+# 'go build' creates an executable named 'todarch-cli'
+# change name after extraction to a shorter version.
+TODARCH_CMD=td
 
 if [ -z "$TODARCH_HOME" ]; then
     TODARCH_HOME="$HOME/.todarch"
@@ -26,7 +26,7 @@ if [ -d "$TODARCH_HOME" ]; then
 	echo ""
 	echo " Please consider running the following if you need to upgrade."
 	echo ""
-	echo "    $ todarch selfupdate force"
+	echo "    $ ${TODARCH_CMD} selfupdate "
 	echo ""
 	echo "======================================================================================================"
 	echo ""
@@ -58,19 +58,11 @@ if [ -z $(which curl) ]; then
 	exit 0
 fi
 
-mkdir "$TODARCH_HOME"
-
-TODARCH_PLATFORM=$(uname)
-echo "Retrieving the latest version tag..."
-TODARCH_VERSION=$(curl -s https://api.github.com/repos/todarch/todarch-cli/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
-echo "Latest version: $TODARCH_VERSION"
-
-app_name=todarch-cli
-version_number=$(echo $TODARCH_VERSION | tr -d 'v')
 os_name=$(uname)
 bit_type=$(uname -m)
 extension="tar.gz"
-case "$(uname)" in
+
+case "$(uname)" in # uname -s
     Linux* | Darwin*)
         extension="tar.gz"
         ;;
@@ -79,23 +71,61 @@ case "$(uname)" in
         os_name=Windows
         ;;
 esac
-artifact_name=${app_name}_${version_number}_${os_name}_${bit_type}.${extension}
-echo $artifact_name
 
-todarch_artifact=${TMPDIR}/${artifact_name}
+RELEASES_URL="https://github.com/todarch/todarch-cli/releases"
+LOCAL_ARCHIVE="/tmp/todarch-cli.${extension}"
+
+last_version() {
+  curl -sL -o /dev/null -w %{url_effective} "$RELEASES_URL/latest" |
+    rev |
+    cut -f1 -d'/'|
+    rev
+}
+
+download() {
+  test -z "$VERSION" && VERSION="$(last_version)"
+  test -z "$VERSION" && {
+    echo "Unable to get todarch version." >&2
+    exit 1
+  }
+  version_number=$(echo "$VERSION" | tr -d 'v')
+  rm -f "$TAR_FILE"
+  REMOTE_ARCHIVE="$RELEASES_URL/download/$VERSION/todarch-cli_${version_number}_${os_name}_${bit_type}.${extension}"
+  echo "Going to download '$REMOTE_ARCHIVE'"
+  curl -L --progress-bar -o "$LOCAL_ARCHIVE" "$REMOTE_ARCHIVE"
+}
 
 echo "Download executable archive..."
-curl --location --progress-bar "https://github.com/todarch/todarch-cli/releases/download/${TODARCH_VERSION}/$artifact_name" > "$todarch_artifact"
+download
+
+mkdir "$TODARCH_HOME"
 
 echo "Extracting executable archive..."
 if [ ${extension} == 'zip' ]; then
-    unzip -qt "$todarch_artifact"
+    unzip -qo "$LOCAL_ARCHIVE" -d "$TODARCH_HOME"
 else
-    tar zxf "$todarch_artifact" --directory ${TODARCH_HOME}
+    tar zxf "$LOCAL_ARCHIVE" --directory "$TODARCH_HOME"
 fi
 
-mv ${TODARCH_HOME}/todarch-cli ${TODARCH_HOME}/todarch
+echo "Looking for extracted executable..."
+if [ -z $(which $TODARCH_HOME/todarch-cli) ]; then
+	echo "Not found."
+	echo ""
+	echo "======================================================================================================"
+	echo "Something went wrong while extracting the archived content."
+	echo "======================================================================================================"
+	echo ""
+	exit 0
+fi
 
+mv ${TODARCH_HOME}/todarch-cli ${TODARCH_HOME}/${TODARCH_CMD}
+todarch_config_file=$TODARCH_HOME/config.yml
+
+echo "Prime the config file..."
+touch "$todarch_config_file"
+echo "todarchApiBase: https://api.todarch.com" >> "$todarch_config_file"
+
+todarch_bash_profile="${HOME}/.bash_profile"
 
 echo "Attempt update of .bash_profile..."
 if [[ -z $(grep 'TODARCH_HOME' "$todarch_bash_profile") ]]; then
@@ -103,7 +133,7 @@ if [[ -z $(grep 'TODARCH_HOME' "$todarch_bash_profile") ]]; then
     echo "Added TODARCH_HOME to $todarch_bash_profile"
 fi
 
-echo -e "\n\n\nAll done!\n\n"
+echo -e "\n\nAll done!\n\n"
 
 echo "Please open a new terminal, or run the following in the existing one:"
 echo ""
@@ -111,6 +141,6 @@ echo "    source $todarch_bash_profile"
 echo ""
 echo "Then issue the following command:"
 echo ""
-echo "    todarch help"
+echo "    ${TODARCH_CMD} help"
 echo ""
 echo "Enjoy!!!"
